# Generated by Django 2.1.3 on 2019-02-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggested', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Just',
        ),
    ]
