# Generated by Django 2.1.3 on 2019-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suggested', '0002_delete_just'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField()),
                ('owner_id', models.SmallIntegerField()),
                ('date', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('from_id', models.PositiveIntegerField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
