# Generated by Django 2.1.3 on 2019-02-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0001_initial'),
        ('suggested', '0003_suggested'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSugg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filmbase.Film')),
                ('sugg_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggested.Suggested')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='videosugg',
            unique_together={('video_id', 'owner_id')},
        ),
    ]
