# Generated by Django 2.1.3 on 2019-03-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested', '0004_auto_20190213_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggested',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
