# Generated by Django 2.1.3 on 2019-02-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vkposts', '0008_vkpost_copy'),
        ('video', '0002_auto_20190205_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('vkpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vkposts.VKPost')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('vkposts.vkpost',),
        ),
        migrations.CreateModel(
            name='VideoSugg',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.Video')),
                ('sugg_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggested.Suggested')),
            ],
            bases=('video.video',),
        ),
    ]
