# Generated by Django 2.1.3 on 2019-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggested',
            name='author',
        ),
        migrations.AddField(
            model_name='suggested',
            name='from_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
