# Generated by Django 2.1.3 on 2019-02-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested', '0003_auto_20190212_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggested',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
