# Generated by Django 2.1.3 on 2019-02-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190205_1753'),
        ('suggested', '0007_auto_20190213_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSugg',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.Video')),
                ('sugg_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggested.Suggested')),
            ],
            bases=('video.video',),
        ),
    ]
