# Generated by Django 2.1.3 on 2019-02-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0010_auto_20190212_1639'),
        ('suggested', '0008_videosugg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggested',
            name='vkpost_ptr',
        ),
        migrations.RemoveField(
            model_name='videosugg',
            name='sugg_post',
        ),
        migrations.RemoveField(
            model_name='videosugg',
            name='video_ptr',
        ),
        migrations.DeleteModel(
            name='Suggested',
        ),
        migrations.DeleteModel(
            name='VideoSugg',
        ),
    ]
