# Generated by Django 2.1.3 on 2019-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0010_auto_20190212_1639'),
        ('suggested', '0010_suggested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Just',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nothing', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='suggested',
            name='vkpost_ptr',
        ),
        migrations.DeleteModel(
            name='Suggested',
        ),
    ]
