# Generated by Django 2.1.3 on 2019-05-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0004_auto_20190430_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='k10',
            field=models.PositiveSmallIntegerField(blank=True, default=10),
        ),
    ]
