# Generated by Django 2.1.3 on 2019-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0005_concept_k10'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='calc_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
