# Generated by Django 2.1.3 on 2019-05-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0005_auto_20190425_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfielddjangodbmodelsfieldspositiveintegerfield', max_length=150, unique=True),
        ),
    ]
