# Generated by Django 2.1.3 on 2019-05-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0007_auto_20190513_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(default='built-in-function-id-djangodbmodelsfieldscharfield-djangodbmodelsfieldspositiveintegerfield', max_length=150),
        ),
    ]
