# Generated by Django 2.1.3 on 2019-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0008_auto_20190513_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
