# Generated by Django 2.1.3 on 2019-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0009_auto_20190513_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
