# Generated by Django 2.1.3 on 2019-04-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmbase', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film_List_Elem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmbase.Film')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Shot')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('intro', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('fin_count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='film_list_elem',
            name='owner_list',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.List'),
        ),
    ]
