# Generated by Django 2.1.3 on 2019-04-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film_list_elem',
            old_name='image',
            new_name='elem_image',
        ),
    ]
