# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='fin_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
