# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='videovk',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='inbox',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Film'),
        ),
    ]
