# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180414_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('kp_id', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('hd', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='kp_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
