# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180515_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='kp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Film'),
        ),
    ]
