# Generated by Django 2.1.3 on 2019-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_list_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
