# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180515_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='kp_id',
            new_name='film',
        ),
    ]
