# Generated by Django 2.1.3 on 2019-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190418_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_list_elem',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='film_list_elem',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
