# Generated by Django 2.1.3 on 2019-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190418_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='numered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film_list_elem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
