# Generated by Django 2.1.3 on 2019-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='single_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
