# Generated by Django 2.1.3 on 2019-04-19 17:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190419_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
