# Generated by Django 2.1.3 on 2019-05-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190524_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='elem_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
