# Generated by Django 2.1.3 on 2019-10-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190524_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_list_elem',
            name='maybe',
            field=models.BooleanField(default=False),
        ),
    ]
