# Generated by Django 2.1.3 on 2019-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190418_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
