# Generated by Django 2.1.3 on 2019-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_shot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='image',
            field=models.ImageField(upload_to='uploads/shots/'),
        ),
    ]
