# Generated by Django 2.1.3 on 2019-04-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20190419_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot',
            old_name='film',
            new_name='movie',
        ),
    ]
