# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.CharField(blank=True, default='', max_length=400)),
                ('kp_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('title_en', models.CharField(blank=True, max_length=150)),
                ('image', models.CharField(blank=True, default='', max_length=400)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('videovk', models.CharField(blank=True, max_length=400, null=True)),
                ('material', models.TextField(blank=True)),
                ('kp_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('votes', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('kp_plot', models.TextField(blank=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filmbase.Director')),
            ],
        ),
    ]
