# Generated by Django 2.1.3 on 2019-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title_alter',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
