# Generated by Django 2.1.3 on 2019-04-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0003_film_first_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='kp_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
