# Generated by Django 2.1.3 on 2019-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0008_auto_20190513_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='moratory10',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
