# Generated by Django 2.1.3 on 2019-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmbase', '0010_auto_20190529_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='last_search',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
