# Generated by Django 2.1.3 on 2019-02-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0002_auto_20190205_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElseAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.PositiveIntegerField()),
                ('owner_id', models.SmallIntegerField()),
                ('sizes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VKAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VKPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField()),
                ('owner_id', models.SmallIntegerField()),
                ('date', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('reposts', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='vkatt',
            name='post_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkposts.VKPost'),
        ),
        migrations.AddField(
            model_name='videoatt',
            name='host_att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkposts.VKAtt'),
        ),
        migrations.AddField(
            model_name='videoatt',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video.Video'),
        ),
        migrations.AddField(
            model_name='photoatt',
            name='host_att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkposts.VKAtt'),
        ),
        migrations.AddField(
            model_name='photoatt',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vkposts.Photo'),
        ),
        migrations.AddField(
            model_name='elseatt',
            name='host_att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkposts.VKAtt'),
        ),
    ]
