# Generated by Django 2.1.3 on 2019-02-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elseatt',
            name='host_att',
        ),
        migrations.RemoveField(
            model_name='photoatt',
            name='host_att',
        ),
        migrations.RemoveField(
            model_name='photoatt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='videoatt',
            name='host_att',
        ),
        migrations.RemoveField(
            model_name='videoatt',
            name='id',
        ),
        migrations.AddField(
            model_name='photoatt',
            name='vkatt_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vkposts.VKAtt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoatt',
            name='vkatt_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vkposts.VKAtt'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ElseAtt',
        ),
    ]
