# Generated by Django 2.1.3 on 2019-02-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0002_auto_20190206_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElseAtt',
            fields=[
                ('vkatt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vkposts.VKAtt')),
                ('att_text', models.TextField()),
            ],
            bases=('vkposts.vkatt',),
        ),
    ]
