# Generated by Django 2.1.3 on 2019-02-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0003_elseatt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='sizes',
            new_name='full_att',
        ),
    ]
