# Generated by Django 2.1.3 on 2019-02-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0004_auto_20190206_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoatt',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vkposts.Photo'),
        ),
        migrations.AlterField(
            model_name='videoatt',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.Video'),
        ),
    ]
