# Generated by Django 2.1.3 on 2019-02-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0005_auto_20190206_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkpost',
            name='show_in_raw_rating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vkpost',
            name='widget',
            field=models.TextField(blank=True),
        ),
    ]
