# Generated by Django 2.1.3 on 2019-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkposts', '0007_auto_20190207_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkpost',
            name='copy',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
