# Generated by Django 2.1.3 on 2019-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vid',
            new_name='video_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='prop_title',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('video_id', 'owner_id')},
        ),
    ]
