# Generated by Django 2.1.3 on 2019-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190205_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timeout',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
