# Generated by Django 2.1.3 on 2019-02-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='timeout',
        ),
    ]
